# Use an official Node.js runtime as the base image
FROM node:18.17-slim as dev-stage

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY zora/package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY ./zora .

# Build the Vue.js app
#RUN npm run build

# Development environment
FROM dev-stage as build-stage

# Export port 3000
EXPOSE 3000

# Build the Vue.js app with hot-reloading for dev
CMD ["npm", "run", "dev", "--host"]
